          - amazon.aws.ec2_instance:
                  region: "{{ region }}"
                  image_id: "{{ image_id }}"
                  instance_type: "{{ instance_type }}"
                  count: "{{ instance_count }}"
                  vpc_subnet_id: "{{ subnet_id }}"
                  security_group: "{{ security_group }}"
                  key_name: "{{ key }}"
                  tags:
                          Name: slave
                  state: present
                  aws_access_key: "{{ aws_access_key }}"
                  aws_secret_key: "{{ aws_secret_key }}"
            register: y
 
